---
  - name: Install git
    yum: name=git state=present

  - name: Install nvm
    sudo: yes
    sudo_user: "{{ user.name }}"
    git: repo=https://github.com/creationix/nvm.git dest={{ user.home }}/.nvm version={{ nvm.version }}

  - name: Source nvm in ~/.bashrc
    sudo: yes
    sudo_user: "{{ user.name }}"
    lineinfile: >
      dest="{{ user.home }}/.bashrc"
      line="source {{ user.home }}/.nvm/nvm.sh"

  - name: Install {{ nodejs.version }}
    command: sudo -iu {{ user.name }} nvm install {{ nodejs.version }}
    register: nvm_install_result
    changed_when: "'is already installed.' not in nvm_install_result.stdout"

  - name: Check if {{ nodejs.version }} is the default node version
    shell: sudo -iu {{ user.name }} nvm ls | grep -e 'default -> {{ nodejs.version }}'
    register: nvm_check_default
    changed_when: False
    ignore_errors: True

  - name: Set default node version to {{ nodejs.version }}
    command: sudo -iu {{ user.name }} nvm alias default {{ nodejs.version }}
    when: nvm_check_default|failed